In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

## [1] Data Loading

In [3]:
df = pd.read_csv('data/restaurant_sales_data.csv')

## [2] Data Understanding

In [13]:
df.shape

(17534, 9)

In [4]:
df.head(5)

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,NaN,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [ ]:
df.info()
# There are missing values at these columns [Item, Price, Quantity, Order Total, Payment Method]
# Columns with their datatypes have to be modified [Order Date]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        17534 non-null  object
 1   Customer ID     17534 non-null  object
 2   Category        17534 non-null  object
 3   Item            15776 non-null  object
 4   Price           16658 non-null  float64
 5   Quantity        17104 non-null  float64
 6   Order Total     17104 non-null  float64
 7   Order Date      17534 non-null  object
 8   Payment Method  16452 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

In [9]:
df.describe()
# [Price, Order Total] have outliers

              Price      Quantity   Order Total
count  16658.000000  17104.000000  17104.000000
mean       6.586325      3.014149     19.914494
std        4.834652      1.414598     18.732549
min        1.000000      1.000000      1.000000
25%        3.000000      2.000000      7.500000
50%        5.000000      3.000000     15.000000
75%        7.000000      4.000000     25.000000
max       20.000000      5.000000    100.000000

## [3] Data Cleaning

### 1. Standardize the columns names

In [11]:
df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')

In [12]:
df.head(5)

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,NaN,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

### 2. Drop Unuseful columns for Analysis

In [16]:
df.drop(columns=['order_id'], inplace=True)

In [17]:
df.head(5)

,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card
1,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,CUST_075,Drinks,NaN,NaN,2.0,5.0,2022-08-09,Credit Card
4,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

### 3. Handle missing values

In [18]:
numerical = ['price', 'quantity', 'order_total']
categorical = ['customer_id', 'category', 'item', 'order_date']

In [20]:
df.isna().sum().sort_values(ascending=False)

item              1758
payment_method    1082
price              876
quantity           430
order_total        430
category             0
customer_id          0
order_date           0
dtype: int64

In [22]:
for col in numerical:
    fig = px.box(df, x=col, title=f'{col} boxblot')
    fig.show()

In [29]:
def calc_outliers_perct(col):
    col = col.dropna()

    q1 = col.quantile(0.25)
    q3 = col.quantile(0.75)
    iqr = q3-q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    return ((col < lower_bound) | (col > upper_bound)).mean() * 100

In [30]:
outliers_in_perct = {col : calc_outliers_perct(df[col]) for col in numerical}

In [31]:
outliers_in_perct

{'price': np.float64(13.873214071317086),
 'quantity': np.float64(0.0),
 'order_total': np.float64(8.237839101964454)}

In [32]:
for col in numerical:
    df[col] = df[col].fillna(df[col].median())

In [34]:
df.isna().sum().sort_values(ascending=False)

item              1758
payment_method    1082
category             0
customer_id          0
price                0
quantity             0
order_total          0
order_date           0
dtype: int64

In [35]:
payment_mode = df['payment_method'].mode()[0]
df['payment_method'] = df['payment_method'].fillna(payment_mode)

In [39]:
df['item'] = df.groupby('category')['item'].transform(
    lambda category: category.fillna(category.mode()[0] if not category.mode().empty else "Unknown")
)

In [40]:
df.isna().sum().sort_values(ascending=False)

customer_id       0
category          0
item              0
price             0
quantity          0
order_total       0
order_date        0
payment_method    0
dtype: int64

### 4. Fix DataTypes

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     17534 non-null  object
 1   category        17534 non-null  object
 2   item            17534 non-null  object
 3   price           17534 non-null  float64
 4   quantity        17534 non-null  float64
 5   order_total     17534 non-null  float64
 6   order_date      17534 non-null  object
 7   payment_method  17534 non-null  object
dtypes: float64(3), object(5)
memory usage: 1.1+ MB

In [47]:
df.order_date.unique()

array(['2023-12-21', '2023-05-19', '2023-09-27', '2022-08-09',
       '2022-05-15', '2022-07-20', '2022-08-19', '2023-02-15',
       '2023-12-16', '2022-08-07', '2023-12-09', '2023-10-30',
       '2023-04-11', '2023-08-18', '2022-06-08', '2022-08-28',
       '2022-05-01', '2023-09-01', '2022-11-13', '2023-06-08',
       '2023-02-21', '2023-02-01', '2023-05-09', '2023-09-14',
       '2023-03-18', '2023-05-18', '2023-09-05', '2022-02-02',
       '2023-07-30', '2023-01-31', '2023-02-28', '2022-11-19',
       '2023-05-03', '2023-04-20', '2023-09-18', '2022-04-08',
       '2023-07-29', '2023-10-16', '2022-02-09', '2023-08-17',
       '2022-04-13', '2023-07-21', '2023-12-03', '2023-09-16',
       '2023-02-11', '2023-02-05', '2022-01-16', '2023-11-21',
       '2022-10-08', '2023-03-01', '2023-05-23', '2022-08-11',
       '2022-08-03', '2022-12-20', '2022-09-12', '2022-06-24',
       '2023-08-04', '2022-03-11', '2023-09-28', '2022-08-12',
       '2023-01-23', '2023-07-08', '2022-12-07', '2023-08-01',
       '2023-06-30', '2022-05-27', '2022-04-07', '2022-10-02',
       '2023-06-01', '2023-05-24', '2023-04-01', '2023-01-19',
       '2022-08-18', '2022-01-11', '2022-05-13', '2022-05-29',
       '2022-07-15', '2023-06-07', '2022-07-08', '2022-10-28',
       '2022-09-15', '2023-03-30', '2023-04-13', '2022-04-01',
       '2022-03-28', '2023-01-28', '2022-11-14', '2022-07-27',
       '2022-05-25', '2023-08-15', '2022-02-05', '2022-02-18',
       '2023-07-27', '2023-03-10', '2023-05-10', '2022-07-29',
       '2023-02-26', '2023-03-24', '2023-08-22', '2023-03-09',
       '2023-06-10', '2023-10-29', '2022-10-14', '2023-11-26',
       '2022-03-24', '2023-11-22', '2023-01-21', '2022-01-05',
       '2023-05-26', '2022-09-29', '2022-05-30', '2023-02-13',
       '2023-08-24', '2022-12-31', '2022-12-09', '2022-01-01',
       '2023-05-07', '2023-11-10', '2023-04-03', '2022-12-24',
       '2022-11-22', '2023-04-19', '2022-01-06', '2023-11-30',
       '2023-04-22', '2022-12-28', '2022-03-27', '2022-03-04',
       '2023-03-29', '2023-06-18', '2022-06-02', '2022-10-27',
       '2022-09-22', '2022-10-01', '2022-02-12', '2022-08-15',
       '2022-04-24', '2023-04-10', '2022-06-28', '2022-06-22',
       '2023-12-25', '2023-03-14', '2023-11-11', '2023-02-08',
       '2022-08-06', '2023-12-11', '2022-07-13', '2023-12-08',
       '2022-06-13', '2023-10-15', '2023-02-07', '2022-02-26',
       '2022-12-05', '2022-07-22', '2023-06-11', '2023-07-16',
       '2023-12-07', '2023-05-21', '2022-06-16', '2022-04-16',
       '2022-12-19', '2023-06-25', '2022-10-13', '2022-10-16',
       '2023-02-03', '2023-10-11', '2022-11-17', '2022-09-10',
       '2023-09-08', '2023-11-27', '2022-05-03', '2022-09-26',
       '2022-05-28', '2022-05-11', '2022-11-26', '2022-04-12',
       '2023-12-14', '2022-09-16', '2022-11-20', '2023-05-27',
       '2022-09-03', '2023-06-22', '2023-05-28', '2022-12-06',
       '2022-04-29', '2022-03-18', '2022-04-11', '2022-07-04',
       '2023-01-06', '2022-05-14', '2022-12-14', '2022-07-01',
       '2022-10-03', '2023-10-25', '2022-03-13', '2023-04-27',
       '2023-05-06', '2023-01-09', '2022-06-27', '2023-02-19',
       '2023-03-11', '2022-06-20', '2023-04-18', '2022-03-23',
       '2023-03-19', '2023-06-29', '2022-11-16', '2022-02-07',
       '2022-02-14', '2023-01-18', '2022-08-31', '2023-01-20',
       '2023-03-04', '2022-11-29', '2022-07-06', '2023-07-06',
       '2023-02-18', '2023-04-15', '2022-11-28', '2023-09-26',
       '2023-11-20', '2023-09-12', '2023-02-04', '2022-12-11',
       '2022-11-23', '2022-03-15', '2023-08-14', '2023-02-23',
       '2022-10-21', '2023-04-12', '2022-05-26', '2023-05-31',
       '2023-11-15', '2022-06-21', '2022-05-05', '2023-06-05',
       '2023-03-27', '2022-10-05', '2023-10-12', '2023-09-30',
       '2023-11-25', '2022-01-31', '2023-01-04', '2023-11-05',
       '2022-08-29', '2023-04-25', '2023-09-22', '2022-03-17',
       '2023-07-07', '2022-10-11', '2023-05-05', '2023-10-20',
       '2022-03-29', '2023-07-25', '2022-05-08', '2022-09-09',
       '2023-07-13', '2023-06-12', '2023-10-06', '2022-11-07',
       '2022-12-08', '2022-10-20', '2022-04-22', '2022-11-06',
       '2023-12-30', '2022-04-15', '2022-07-26', '2023-01-16',
       '2023-08-12', '2023-08-28', '2023-06-19', '2022-01-18',
       '2023-10-22', '2022-03-26', '2023-09-03', '2022-05-22',
       '2023-08-25', '2022-10-23', '2023-11-14', '2022-03-21',
       '2022-03-25', '2023-07-01', '2023-11-19', '2022-10-12',
       '2022-01-24', '2023-08-10', '2023-09-19', '2022-01-29',
       '2022-07-17', '2023-06-28', '2022-05-24', '2022-01-15',
       '2023-10-24', '2023-11-09', '2023-11-13', '2023-02-12',
       '2023-09-24', '2023-07-23', '2022-09-02', '2022-12-29',
       '2023-09-29', '2023-05-04', '2022-04-20', '2022-12-21',
       '2022-07-09', '2023-11-01', '2022-06-29', '2023-03-23',
       '2023-05-22', '2022-11-30', '2023-04-21', '2022-10-25',
       '2022-02-08', '2022-11-05', '2022-05-21', '2022-07-24',
       '2023-10-31', '2022-10-04', '2023-10-18', '2022-07-28',
       '2022-06-30', '2022-09-20', '2023-05-14', '2022-08-05',
       '2023-03-22', '2023-04-16', '2022-09-04', '2022-04-03',
       '2023-02-16', '2022-02-01', '2022-11-27', '2023-07-17',
       '2023-09-20', '2022-03-01', '2023-09-15', '2023-05-02',
       '2023-08-02', '2022-07-18', '2022-10-07', '2022-02-10',
       '2023-11-18', '2022-10-09', '2022-08-26', '2023-12-18',
       '2023-10-19', '2023-08-06', '2022-10-17', '2023-09-02',
       '2023-11-04', '2022-03-07', '2022-01-26', '2023-07-10',
       '2022-02-28', '2023-10-07', '2023-12-02', '2023-06-04',
       '2022-06-19', '2022-09-01', '2022-04-17', '2022-01-20',
       '2023-11-29', '2022-02-16', '2022-01-07', '2022-02-25',
       '2022-08-21', '2022-04-05', '2022-05-09', '2022-06-07',
       '2023-03-15', '2022-01-13', '2023-12-06', '2023-10-23',
       '2023-01-26', '2022-03-19', '2022-02-27', '2023-04-17',
       '2023-05-17', '2023-03-03', '2022-07-02', '2022-04-14',
       '2022-01-02', '2022-04-06', '2022-04-19', '2022-06-23',
       '2023-08-23', '2022-07-30', '2022-12-25', '2022-02-15',
       '2023-06-16', '2023-10-05', '2023-02-09', '2023-08-03',
       '2023-04-06', '2023-06-17', '2022-11-01', '2023-07-22',
       '2023-02-25', '2023-08-20', '2023-03-07', '2022-10-10',
       '2023-08-13', '2023-12-26', '2022-06-06', '2023-06-27',
       '2023-07-28', '2023-10-28', '2022-11-12', '2022-01-27',
       '2022-08-01', '2022-05-17', '2022-12-18', '2022-12-16',
       '2022-06-03', '2023-07-31', '2023-08-29', '2023-09-21',
       '2022-08-10', '2022-09-11', '2023-03-06', '2022-07-16',
       '2022-01-08', '2022-03-09', '2023-10-04', '2023-11-12',
       '2022-03-20', '2022-03-22', '2023-03-02', '2023-05-01',
       '2022-07-23', '2022-09-08', '2022-10-22', '2023-02-24',
       '2022-05-12', '2023-12-17', '2022-06-01', '2023-02-22',
       '2023-11-06', '2022-12-02', '2022-05-23', '2023-01-13',
       '2023-03-25', '2023-02-17', '2023-07-20', '2022-02-22',
       '2023-05-30', '2023-06-14', '2022-03-31', '2023-03-08',
       '2023-07-15', '2023-04-24', '2022-08-08', '2023-10-10',
       '2022-10-06', '2023-10-26', '2022-09-27', '2022-08-27',
       '2023-10-09', '2023-10-14', '2023-08-30', '2022-05-18',
       '2023-03-21', '2023-04-28', '2022-12-03', '2023-06-15',
       '2022-12-17', '2022-04-02', '2023-11-23', '2022-08-30',
       '2023-10-02', '2022-05-07', '2022-01-30', '2023-05-20',
       '2023-12-04', '2022-06-09', '2022-01-03', '2023-12-15',
       '2022-10-31', '2022-12-22', '2023-09-17', '2022-11-15',
       '2023-01-11', '2022-07-19', '2022-05-02', '2023-01-17',
       '2022-09-28', '2022-10-26', '2022-09-06', '2022-07-14',
       '2023-07-12', '2022-07-11', '2023-03-05', '2022-05-31',
       '2023-03-28', '2022-04-10', '2023-01-30', '2023-05-08',
       '2022-11-09', '2022-08-20', '2022-08-13', '2022-08-04',
       '2023-09-11', '2022-12-23', '2023-01-10', '2022-11-24',
       '2023-04-02', '2022-09-19', '2023-10-17', '2023-12-27',
       '2023-01-03', '2022-08-22', '2023-03-17', '2022-05-16',
       '2022-10-29', '2023-07-04', '2023-09-25', '2023-02-27',
       '2022-10-18', '2022-11-03', '2023-01-01', '2023-06-09',
       '2023-04-23', '2023-10-27', '2022-04-04', '2023-12-05',
       '2023-07-11', '2023-04-04', '2022-04-25', '2023-08-09',
       '2023-08-11', '2023-03-26', '2022-01-25', '2023-08-05',
       '2022-12-15', '2022-02-23', '2023-06-26', '2022-07-03',
       '2023-08-31', '2023-12-23', '2023-12-12', '2022-03-02',
       '2022-05-10', '2022-01-12', '2023-03-12', '2023-01-14',
       '2023-11-16', '2023-05-25', '2023-07-14', '2023-11-24',
       '2022-05-19', '2023-11-08', '2023-10-13', '2022-06-18',
       '2023-08-26', '2022-12-30', '2022-11-08', '2023-01-29',
       '2022-11-21', '2022-02-21', '2022-10-24', '2022-09-25',
       '2022-01-17', '2022-03-30', '2022-03-16', '2022-09-17',
       '2022-01-09', '2023-10-03', '2022-06-26', '2022-04-23',
       '2023-01-12', '2022-11-25', '2022-01-22', '2022-01-28',
       '2023-11-28', '2023-01-05', '2022-09-18', '2022-10-15',
       '2022-11-10', '2023-07-18', '2022-06-11', '2023-09-13',
       '2023-07-24', '2023-04-30', '2023-01-08', '2022-07-21',
       '2022-02-03', '2022-03-08', '2022-09-05', '2022-08-25',
       '2022-12-04', '2022-06-10', '2022-06-04', '2022-04-26',
       '2023-01-22', '2023-09-06', '2022-03-05', '2022-02-04',
       '2022-09-13', '2022-12-12', '2022-05-04', '2023-10-01',
       '2023-05-11', '2023-02-02', '2023-09-09', '2022-06-25',
       '2022-01-23', '2022-12-01', '2023-08-08', '2022-02-17',
       '2022-09-24', '2022-10-19', '2022-04-30', '2022-01-10',
       '2022-07-25', '2022-02-11', '2023-12-13', '2022-12-10',
       '2023-01-24', '2022-04-28', '2022-03-03', '2022-08-24',
       '2022-09-23', '2022-05-20', '2023-04-26', '2022-02-19',
       '2022-06-05', '2023-11-07', '2022-12-13', '2023-08-16',
       '2022-10-30', '2023-01-25', '2023-10-21', '2023-11-17',
       '2022-08-23', '2023-04-14', '2023-06-23', '2023-06-20',
       '2023-07-19', '2023-12-19', '2022-08-17', '2022-09-21',
       '2023-06-24', '2023-03-31', '2022-01-19', '2023-04-08',
       '2023-04-05', '2023-05-15', '2023-04-09', '2023-01-07',
       '2022-01-04', '2022-04-09', '2023-01-02', '2023-12-24',
       '2023-05-13', '2023-12-22', '2022-03-12', '2023-12-29',
       '2023-06-06', '2022-12-26', '2023-08-19', '2022-11-11',
       '2022-11-04', '2023-09-23', '2022-09-30', '2023-05-12',
       '2023-06-02', '2023-12-31', '2022-03-10', '2023-11-03',
       '2023-07-26', '2022-03-14', '2023-12-10', '2022-06-14',
       '2023-03-13', '2022-03-06', '2022-02-13', '2023-03-20',
       '2022-08-16', '2022-07-07', '2023-02-06', '2023-09-07',
       '2023-12-01', '2023-07-09', '2022-01-14', '2022-02-06',
       '2023-02-10', '2022-11-18', '2022-12-27', '2022-06-17',
       '2023-12-20', '2023-06-21', '2023-10-08', '2023-01-15',
       '2023-05-29', '2023-06-13', '2023-03-16', '2022-07-05',
       '2022-09-07', '2022-05-06', '2022-01-21', '2023-08-21',
       '2022-02-24', '2022-06-12', '2022-09-14', '2022-04-18',
       '2023-04-07', '2022-04-21', '2023-09-04', '2022-07-12',
       '2022-02-20', '2022-11-02', '2023-07-02', '2022-08-02',
       '2023-12-28', '2022-07-31', '2022-07-10', '2022-04-27',
       '2022-08-14', '2023-07-03', '2023-04-29', '2023-01-27',
       '2023-05-16', '2023-08-27', '2023-09-10', '2023-02-20',
       '2023-02-14', '2023-08-07', '2023-11-02', '2023-06-03',
       '2022-06-15', '2023-07-05'], dtype=object)

In [48]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [54]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day'] = df['order_date'].dt.day
df['order_day_of_week'] = df['order_date'].dt.dayofweek
df['order_day_name'] = df['order_date'].dt.day_name()
df['is_weekend'] = df['order_day_of_week'].isin([5, 6]).astype(int)

In [55]:
df.head(10)

,customer_id,category,item,price,quantity,order_total,order_date,payment_method,order_year,order_month,order_day,order_day_of_week,order_day_name,is_weekend
0,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card,2023,12,21,3,Thursday,0
1,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet,2023,5,19,4,Friday,0
2,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card,2023,9,27,2,Wednesday,0
3,CUST_075,Drinks,Water,5.0,2.0,5.0,2022-08-09,Credit Card,2022,8,9,1,Tuesday,0
4,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash,2022,5,15,6,Sunday,1
5,CUST_031,Main Dishes,Salmon,18.0,5.0,90.0,2022-07-20,Digital Wallet,2022,7,20,2,Wednesday,0
6,CUST_071,Side Dishes,Garlic Bread,4.0,5.0,20.0,2022-08-19,Credit Card,2022,8,19,4,Friday,0
7,CUST_077,Main Dishes,Pasta Alfredo,15.0,3.0,45.0,2023-02-15,Cash,2023,2,15,2,Wednesday,0
8,CUST_083,Desserts,Ice Cream,6.0,2.0,12.0,2023-12-16,Cash,2023,12,16,5,Saturday,1
9,CUST_085,Main Dishes,Vegetarian Platter,14.0,5.0,70.0,2022-08-07,Credit Card,2022,8,7,6,Sunday,1

### 5. Remove Duplicates - if existed

In [ ]:
df.duplicated().sum()

np.int64(6)

In [59]:
df.drop_duplicates(inplace=True)

In [60]:
df.duplicated().sum()

np.int64(0)

## [4] EDA